name: angel_diagnostics
description: Support for diagnostics and helpful tools for Angel development.
version: 1.0.0-dev+2
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_diagnostics
dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
  console: ">=2.2.4 <3.0.0"
  logging: ">=0.11.3+1 <0.12.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"