name: angel_diagnostics
description: Support for diagnostics within the Angel framework.
version: 1.0.0-dev+6
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_diagnostics
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0-dev
  console: ^2.0.0
  fnx_profiler:
  logging: ^0.11.0
dev_dependencies:
  http: ^0.11.0
  test: ^0.12.0